const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');
function storage(initial={}){const data=new Map(Object.entries(initial));return {get length(){return data.size},key:i=>[...data.keys()][i],getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k),data}}
function browser(local,extra={}){const listeners={};return {localStorage:local,navigator:{onLine:false},crypto,structuredClone,Date,console,Event:class{constructor(type){this.type=type}},CustomEvent:class{constructor(type,options){this.type=type;this.detail=options.detail}},window:{addEventListener:(type,fn)=>listeners[type]=fn,dispatchEvent:e=>listeners[e.type]?.(e)},document:{addEventListener:()=>{},getElementById:()=>null},listeners,...extra}}
function loadLedger(local,extra={}){const c=browser(local,extra);c.window.AlMahasibMarketOffline={queueTransaction:async()=>{},syncTransactions:async()=>true,syncCloud:async()=>true,status:async()=>({pending:0,transactions:0,conflicts:0,rejected:0}),exportData:async()=>({scope:'company',snapshots:[],outbox:[],transactions:[]}),importData:async()=>{},...extra.runtime};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(root,'public/market-cashier-ledger.js'),'utf8'),c);return c}
async function ledgerTest(){
 const local=storage({almahasib_company_context:JSON.stringify({id:'company'})});let c=loadLedger(local),ledger=c.window.MarketCashierLedger;
 ledger.record('sale',{id:'sale',invoice:'INV1',net:'100.500000',cash:'20.000000',due:'80.500000',paymentType:'representative',party:'أيمن',shiftId:'old',occurredAt:'2025-01-01T00:00:00Z',lines:[]});
 assert.equal(ledger.receivables()[0].balance,'80.500000');
 await ledger.collect('INV1','30.250000',{id:'new',status:'open',cashier:'محمد'});
 assert.equal(ledger.receivables()[0].balance,'50.250000');assert.equal(ledger.cashForShift('old').collections,0);assert.equal(ledger.cashForShift('new').collections,30.25);
 await assert.rejects(()=>ledger.collect('INV1','51',{id:'new',status:'open'}));
 await assert.rejects(()=>ledger.collect('INV1','1',{id:'new',status:'closed'}));
 ledger.record('cash_in',{id:'cash1',amount:'250',shiftId:'new'});assert.equal(ledger.cashForShift('new').cashIn,250);
 // A new runtime/shift, even a year later, must retain the unpaid invoice.
 c=loadLedger(local);ledger=c.window.MarketCashierLedger;assert.equal(ledger.receivables()[0].balance,'50.250000');
 ledger.record('waiting_update',{id:'wait1',waitingId:'w',draft:{id:'w',ref:'انتظار 1',cart:[]},occurredAt:'2025-01-01T00:00:00Z'});
 ledger.record('waiting_close',{id:'close1',waitingId:'w',occurredAt:'2026-01-01T00:00:00Z'});
 ledger.record('waiting_update',{id:'stale',waitingId:'w',draft:{id:'w'},occurredAt:'2025-01-01T00:00:00Z'});assert.equal(ledger.read('held_sales').length,0);
 const backup=await ledger.backup();assert.equal(backup.companyScope,'company');assert(!Object.keys(backup.local).some(k=>k.includes('session')));
 await assert.rejects(()=>ledger.restoreBackup({...backup,companyScope:'foreign'}));
 const fresh=storage({almahasib_company_context:JSON.stringify({id:'company'})});const restored=loadLedger(fresh).window.MarketCashierLedger;await restored.restoreBackup(backup);assert.equal(restored.receivables()[0].balance,'50.250000');
 await restored.collect('INV1','50.250000',{id:'year-later',status:'open'});assert.equal(restored.receivables().length,0);
 console.log('PASS: partial/full debt collection, cross-shift retention, exact amounts, cash additions, closed-waiting replay, backup and company isolation');
}
function fakeDb(){const stores={snapshots:new Map(),outbox:new Map(),transactions:new Map()};const request=value=>{const r={};setImmediate(()=>{r.result=structuredClone(value);r.onsuccess?.()});return r};return {stores,objectStoreNames:{contains:()=>true},transaction(name){const t={objectStore:()=>({get:id=>request(stores[name].get(id)),getAll:()=>request([...stores[name].values()]),put:row=>{stores[name].set(row.id||row.key,structuredClone(row));setImmediate(()=>t.oncomplete?.())}})};return t}}}
async function retryTest(){const db=fakeDb(),local=storage({almahasib_company_context:JSON.stringify({id:'company'})});const c=browser(local,{indexedDB:{open:()=>{const r={result:db};setImmediate(()=>r.onsuccess?.());return r}},BroadcastChannel:class{postMessage(){}},setImmediate});let calls=[],fail=true,active=0,maxActive=0;c.fetch=async(url,opts)=>{const op=JSON.parse(opts.body).operations[0];calls.push(op);active++;maxActive=Math.max(maxActive,active);await new Promise(r=>setImmediate(r));active--;if(fail)throw Error('Response lost');return {ok:true,json:async()=>({results:[{status:'acknowledged'}]})}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(root,'public/market-offline.js'),'utf8'),c);const runtime=c.window.AlMahasibMarketOffline;await runtime.queueTransaction('cash_in',{id:'cash1',amount:'25',shiftId:'s'});c.navigator.onLine=true;await runtime.syncTransactions();fail=false;await Promise.all([runtime.syncTransactions(),runtime.syncTransactions()]);assert.equal(calls.length,2);assert.equal(calls[0].operationId,calls[1].operationId);assert.equal(JSON.stringify(calls[0].payload),JSON.stringify(calls[1].payload));assert.equal(maxActive,1);await runtime.queueTransaction('cash_in',{id:'cash1',amount:'25',shiftId:'s'});assert.equal(calls.length,2);assert.equal((await runtime.exportData()).transactions[0].state,'synced');console.log('PASS: lost response retries same operation/payload, concurrent sync serialized, repeated local flush does not duplicate cash')}
async function serverTest(){let code=fs.readFileSync(path.join(root,'apps/api/src/store/memory-store.js'),'utf8').replace(/^import .*;\r?\n/gm,'').replace('export class MemoryStore','class MemoryStore').replace(/^export \{.*?\};$/gm,'');const c={randomUUID:crypto.randomUUID,structuredClone,AppError:class extends Error{},PERMISSIONS:[],ROLE_TEMPLATES:{},ZERO:0,decimal:Number,decimalString:String,divide:(a,b)=>a/b,multiply:(a,b)=>a*b};vm.createContext(c);vm.runInContext(code+';globalThis.Store=MemoryStore',c);const store=new c.Store(),context={company:{id:'company'},user:{id:'u'},permissions:['sync.use']};const op=(kind,payload)=>({operationId:crypto.randomUUID(),payloadHash:crypto.randomUUID(),type:'market.transaction.'+kind,occurredAt:new Date().toISOString(),payload:{kind,...payload}});await store.pushOperations(context,[op('sale',{id:'s',invoice:'I',net:'100',cash:'20'})]);const collection=op('collection',{id:'c',invoice:'I',amount:'30',shiftId:'shift'});assert.equal((await store.pushOperations(context,[collection]))[0].status,'acknowledged');await store.pushOperations(context,[collection]);assert.equal(store.changes.filter(x=>x.payload.kind==='collection').length,1);assert.equal((await store.pushOperations(context,[op('collection',{id:'bad',invoice:'I',amount:'51',shiftId:'shift'})]))[0].status,'rejected');assert.equal((await store.pushOperations(context,[op('cash_in',{id:'negative',amount:'-1',shiftId:'shift'})]))[0].status,'rejected');const foreign=await store.pullChanges('foreign',0,500);assert.equal(foreign.changes.length,0);console.log('PASS: server payment idempotence, over-collection/negative-cash rejection and company isolation')}
async function cashierTest(){
 const local=storage({almahasib_company_context:JSON.stringify({id:'company'}),'tenant:company:market_shift_main_v1':JSON.stringify({id:'s',status:'open',cashier:'محمد',opening:500,openedAt:'2026-01-01T00:00:00Z',expenses:[{amount:10}]}),'tenant:company:market_catalog_v1':JSON.stringify([{id:'rice',name:'رز',barcode:'6292600000014',price:100,qty:1}])});
 const c=loadLedger(local,{runtime:{saveSnapshot:async()=>{},saveLocalSnapshot:async()=>{}}});const fields={},listeners={};c.document={addEventListener:(name,fn)=>{listeners[name]=fn},querySelector:()=>null,body:{dataset:{standaloneCashier:'true'}},getElementById:id=>fields[id]||(fields[id]={value:'0',style:{},setAttribute(){},focus(){},addEventListener(){}})};c.location={search:'?mode=market'};c.URLSearchParams=URLSearchParams;c.setInterval=()=>1;c.clearInterval=()=>{};c.setTimeout=setTimeout;c.alert=()=>{};c.confirm=()=>true;c.prompt=()=>{throw Error('Unexpected prompt')};
 let source=fs.readFileSync(path.join(root,'public/pos-ui.js'),'utf8').replace('void initialize();','window.testCashier={cart:()=>cart,restoreMarketWork,marketShiftSummary};');vm.runInContext(source,c);
 fields.discountInput={value:'0'};fields.marketPaymentType={value:'credit'};fields.marketParty={value:'أيمن'};fields.marketReceived={value:'25'};
 c.window.PosUI.addMarketProduct('rice');c.window.PosUI.saveMarketWork();const draft=JSON.parse(local.getItem('tenant:company:market_work_main_v1'));assert.equal(draft.cart[0].itemId,'rice');assert.equal(draft.party,'أيمن');
 fields.marketReceived.value='0';c.window.testCashier.restoreMarketWork();assert.equal(fields.marketReceived.value,'25');assert.equal(c.window.testCashier.cart().length,1);
 await c.window.PosUI.completeSale(false);assert.equal(JSON.parse(local.getItem('tenant:company:market_catalog_v1'))[0].qty,0);assert.equal(c.window.testCashier.cart().length,0);assert.equal(c.window.MarketCashierLedger.receivables()[0].balance,'75.000000');assert.equal(c.window.testCashier.marketShiftSummary().expected,515);
 c.window.PosUI.addMarketProduct('rice');assert.equal(c.window.testCashier.cart().length,0);assert.equal(JSON.parse(local.getItem('tenant:company:market_catalog_v1'))[0].qty,0);
 const writes=[];c.navigator.serial={requestPort:async()=>({open:async()=>{},writable:{getWriter:()=>({write:async bytes=>writes.push([...bytes]),releaseLock(){}})}})};
 await c.window.PosUI.connectCashDrawer();const before=c.window.testCashier.marketShiftSummary().expected;
 await c.window.PosUI.openCashDrawerOnly();assert.equal(writes.length,1);assert.deepEqual(writes[0],[27,112,0,50,250]);
 const opens=c.window.MarketCashierLedger.read('drawer_events');assert.equal(opens.filter(x=>x.kind==='drawer_open').length,1);assert.equal(opens.find(x=>x.kind==='drawer_open').amount,undefined);assert.equal(c.window.testCashier.marketShiftSummary().expected,before);
 listeners.keydown({key:'F7',repeat:true,preventDefault(){}});await new Promise(r=>setImmediate(r));assert.equal(writes.length,1);
 console.log('PASS: F7 sends drawer pulse, journals timestamp without money, preserves cash and ignores held-key repeats');
 c.window.PosUI.toggleMarketPrinting();assert.equal(local.getItem('tenant:company:market_printing_enabled'),'false');
 local.setItem('tenant:company:market_catalog_v1',JSON.stringify([{id:'rice',name:'رز',price:100,qty:1}]));fields.marketPaymentType.value='cash';fields.marketReceived.value='100';c.window.PosUI.addMarketProduct('rice');
 listeners.keydown({key:'Control',repeat:false});listeners.keydown({key:'c',ctrlKey:true});listeners.keyup({key:'Control',preventDefault(){}});assert.equal(c.window.testCashier.cart().length,1);
 listeners.keydown({key:'F8',preventDefault(){}});assert.equal(c.window.testCashier.cart().length,1);
 listeners.keydown({key:'Control',repeat:false});listeners.keyup({key:'Control',preventDefault(){}});await new Promise(r=>setTimeout(r,10));assert.equal(c.window.testCashier.cart().length,0);assert.equal(JSON.parse(local.getItem('tenant:company:market_invoices_v1')).length,2);
 console.log('PASS: Ctrl alone completes exactly one sale with printing off; Ctrl+C and F8 do not submit; toggle preference persists');
 console.log('PASS: active cart/payment restored, credit sale deducts stock once, only collected cash enters box, zero-stock product cannot sell');
}
async function saleRouteTest(){
 const source=fs.readFileSync(path.join(root,'apps/api/src/app.js'),'utf8');
 assert(source.includes("import { randomUUID } from 'node:crypto'"));
 const start=source.indexOf("  app.post('/api/v1/market/sale'");const body=source.slice(source.indexOf('async (req, res) => {',start)+'async (req, res) => {'.length,source.indexOf('\n  }));',start));
 const validator=source.slice(source.indexOf('function validateOperation('),source.indexOf('\nfunction ',source.indexOf('function validateOperation(')+1));
 let committed,response;const c={randomUUID:crypto.randomUUID,structuredClone,AppError:class extends Error{},payloadHash:payload=>crypto.createHash('sha256').update(JSON.stringify(payload)).digest('hex'),req:{body:{id:'sale',invoice:'MKT-test',lines:[{itemId:'rice',quantity:'1',unitPrice:'4000'}],net:'4000',cash:'4000'},auth:{company:{id:'company'},session:{deviceId:'web'}}},res:{json:x=>response=x},store:{pullChanges:async()=>({changes:[{entityType:'market.snapshot',payload:{catalog:[{id:'rice',qty:2}]}}],hasMore:false}),pushOperations:async(_,rows)=>{committed=rows;return rows.map(()=>({status:'acknowledged'}))}}};
 vm.createContext(c);await vm.runInContext(validator+'\n(async()=>{'+body+'})()',c);
 assert.equal(response.ok,true);assert.equal(response.snapshot.catalog[0].qty,1);assert.equal(committed[1].payload.cash,'4000');assert.equal(committed.length,2);
 console.log('PASS: online checkout creates snapshot and sale without a global crypto dependency');
}
(async()=>{await ledgerTest();await retryTest();await serverTest();await cashierTest();await saleRouteTest()})().catch(error=>{console.error(error);process.exitCode=1});
