import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { startEnterpriseLocal } from '../../apps/local/enterprise-server.js';

test('payroll approval, cashbox closing, and import landed costs post once to SQLite and the ledger',async()=>{
  const directory=await mkdtemp(join(tmpdir(),'erp-finance-test-'));
  let runtime,cookie='';
  try {
    runtime=await startEnterpriseLocal({dataDirectory:directory,port:33220});
    async function request(path,body,method='POST'){const response=await fetch(runtime.url+path,{headers:{...(body?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{})},...(body?{method,body:JSON.stringify(body)}:{})});if(response.headers.get('set-cookie'))cookie=response.headers.get('set-cookie').split(';')[0];const data=await response.json();return{status:response.status,data};}
    async function create(path,body){const result=await request(path,body);assert.equal(result.status,201,JSON.stringify(result.data));return result.data;}
    const owner={legalName:'شركة الاختبار المالي',ownerName:'المدير',username:'finance_admin',password:'Strong-Offline-123'};
    await create('/api/local/setup',owner);
    assert.equal((await request('/api/v1/auth/login',{companyCode:'local',username:owner.username,password:owner.password})).status,200);
    const ownerCookie=cookie;
    const mainBranch=(await request('/api/v1/company/branches',null,'GET')).data.branches[0];
    assert.equal(mainBranch.code,'main');
    const branch=(await create('/api/v1/company/branches',{code:'SOUTH',name:'الفرع الجنوبي'})).branch;
    assert.equal((await request('/api/v1/company/branches',{code:'SOUTH',name:'مكرر'})).status,409);
    assert.equal((await request('/api/v1/users',{username:'bad_scope',displayName:'نطاق غير صالح',password:'Strong-Invalid-123',roleCode:'warehouse_keeper',scopes:[{type:'branch',id:crypto.randomUUID()}]})).status,400);
    const companyWarehouse=(await create('/api/v1/warehouses',{code:'OTHER-BRANCH',name:'مخزن الشركة'})).warehouse;
    await create('/api/v1/users',{username:'branch_keeper',displayName:'أمين الفرع',password:'Strong-Branch-123',roleCode:'warehouse_keeper',scopes:[{type:'branch',id:branch.id}]});
    assert.equal((await request('/api/v1/auth/login',{companyCode:'local',username:'branch_keeper',password:'Strong-Branch-123'})).status,200);
    assert.equal((await request('/api/v1/warehouses',{code:'DENY-BRANCH',name:'محاولة دون فرع'})).status,403,'branch scoped users must select an authorized branch');
    const branchWarehouse=(await request('/api/v1/warehouses',{code:'BRANCH-WH',name:'مخزن الفرع',branchId:branch.id})).data.warehouse;
    assert.equal((await request('/api/v1/master-data',null,'GET')).data.warehouses.some(warehouse=>warehouse.id===companyWarehouse.id),false,'master data hides warehouses from other branches');
    assert.equal((await request('/api/v1/enterprise/transfers',{operationId:crypto.randomUUID(),sourceWarehouseId:branchWarehouse.id,destinationWarehouseId:companyWarehouse.id,transferNumber:'BRANCH-DENIED'})).status,403,'branch users cannot transfer stock outside their branch');
    cookie=ownerCookie;
    assert.equal((await request(`/api/v1/company/branches/${branch.id}`,{active:false},'PATCH')).status,409,'branch with active warehouses cannot be disabled');
    await create('/api/v1/users',{username:'cashier_test',displayName:'كاشير الاختبار',password:'Strong-Cashier-123',roleCode:'cashier'});
    assert.equal((await request('/api/v1/auth/login',{companyCode:'local',username:'cashier_test',password:'Strong-Cashier-123'})).status,200);
    assert.equal((await request('/api/v1/hr/payroll/cycles',{cycleCode:'DENIED',periodStart:'2026-10-01',periodEnd:'2026-10-31',currency:'IQD'})).status,403);
    assert.equal((await request('/api/v1/import/shipments',{operationId:crypto.randomUUID(),shipmentNumber:'DENIED',containerNumber:'DENIED',supplierId:crypto.randomUUID(),currency:'USD'})).status,403);
    assert.equal((await request('/api/v1/enterprise/customer-credits/apply',{})).status,403,'cashier cannot apply accounting credits');
    cookie=ownerCookie;

    assert.equal((await request('/api/v1/hr/payroll/settings',{workingDaysPerMonth:30,dailyHours:'8',defaultOvertimeMultiplier:'1.5',deductAbsence:true,attendanceRequired:false},'PUT')).status,200);
    const employee=(await create('/api/v1/hr/employees',{code:'EMP-1',fullName:'موظف اختبار',hireDate:'2026-01-01'})).employee;
    await create(`/api/v1/hr/employees/${employee.id}/contracts`,{contractNumber:'CTR-1',startDate:'2026-01-01',basicSalary:'1000000',currency:'IQD'});
    const leave=(await create('/api/v1/hr/leaves',{operationId:crypto.randomUUID(),employeeId:employee.id,leaveType:'annual',startDate:'2026-10-10',endDate:'2026-10-11',reason:'إجازة غير مدفوعة'})).leave;
    assert.equal(leave.status,'pending');
    assert.equal((await request('/api/v1/hr/leaves',{operationId:crypto.randomUUID(),employeeId:employee.id,leaveType:'sick',startDate:'2026-10-11',endDate:'2026-10-12'})).status,409,'overlapping leave requests are blocked');
    assert.equal((await request(`/api/v1/hr/leaves/${leave.id}/decision`,{approved:true,paid:false})).status,200);
    assert.equal((await request(`/api/v1/hr/leaves/${leave.id}/decision`,{approved:true,paid:false})).status,409,'leave cannot be approved twice');
    const overtime=(await create('/api/v1/hr/overtime',{operationId:crypto.randomUUID(),employeeId:employee.id,workDate:'2026-10-15',minutes:60,multiplier:'1.5',reason:'تجربة'})).overtime;
    assert.equal((await request('/api/v1/hr/overtime',{operationId:crypto.randomUUID(),employeeId:employee.id,workDate:'2026-10-15',minutes:30,multiplier:'1.5'})).status,409,'duplicate overtime day is blocked');
    assert.equal((await request(`/api/v1/hr/overtime/${overtime.id}/decision`,{approved:true})).status,200);
    const attendanceId=crypto.randomUUID(),eventTime='2026-10-15T08:00:00.000Z';
    assert.equal((await request('/api/v1/hr/attendance/check-in',{operationId:attendanceId,employeeId:employee.id,eventTime})).status,201);
    assert.equal((await request('/api/v1/hr/attendance/check-in',{operationId:attendanceId,employeeId:employee.id,eventTime})).status,201,'attendance operation retry is idempotent');
    assert.equal((await request('/api/v1/hr/attendance/check-out',{operationId:crypto.randomUUID(),employeeId:employee.id,eventTime:'2026-10-15T16:00:00.000Z'})).status,201);
    await create(`/api/v1/hr/employees/${employee.id}/components`,{code:'ALLOW',name:'مخصص',componentType:'allowance',amount:'100000'});
    await create(`/api/v1/hr/employees/${employee.id}/components`,{code:'DEDUCT',name:'استقطاع',componentType:'deduction',amount:'50000'});
    const advance=(await create(`/api/v1/hr/employees/${employee.id}/advances`,{operationId:crypto.randomUUID(),advanceNumber:'ADV-1',originalAmount:'200000',installmentAmount:'50000',currency:'IQD'})).advance;
    assert.equal(advance.journalEntryId!=null,true);
    const cycle=(await create('/api/v1/hr/payroll/cycles',{cycleCode:'2026-10',periodStart:'2026-10-01',periodEnd:'2026-10-31',currency:'IQD'})).cycle;
    assert.equal((await request('/api/v1/hr/payroll/cycles',{cycleCode:'2026-10-retry',periodStart:'2026-10-01',periodEnd:'2026-10-31',currency:'IQD'})).status,409,'overlapping payroll periods cannot deduct advances twice');
    assert.equal(cycle.lines[0].absenceDays,2);
    assert.equal(cycle.lines[0].absenceDeduction,'66666.666666');
    assert.equal(cycle.lines[0].overtimeAmount,'6249.999960');
    assert.equal(cycle.lines[0].grossAmount,'1039583.333294');
    assert.equal(cycle.lines[0].totalDeductions,'100000.000000');
    assert.equal(cycle.lines[0].netAmount,'939583.333294');
    await request(`/api/v1/hr/payroll/cycles/${cycle.id}/review`,{});
    const approvalId=crypto.randomUUID();
    assert.equal((await request(`/api/v1/hr/payroll/cycles/${cycle.id}/approve`,{operationId:approvalId})).status,200);
    const approvedJournalCount=runtime.store.journalEntries.size;
    await request(`/api/v1/hr/payroll/cycles/${cycle.id}/approve`,{operationId:approvalId});
    assert.equal(runtime.store.journalEntries.size,approvedJournalCount,'approval retry does not duplicate accrual');
    assert.equal(runtime.store.employeeAdvances.get(advance.id).remainingAmount,'150000.000000');
    const payId=crypto.randomUUID();
    assert.equal((await request(`/api/v1/hr/payroll/cycles/${cycle.id}/pay`,{operationId:payId,paymentNumber:'PAY-1'})).status,200);
    const paidJournalCount=runtime.store.journalEntries.size;
    await request(`/api/v1/hr/payroll/cycles/${cycle.id}/pay`,{operationId:payId,paymentNumber:'PAY-1'});
    assert.equal(runtime.store.journalEntries.size,paidJournalCount,'payment retry does not duplicate cash or the journal');
    assert.equal((await request(`/api/v1/hr/payroll/cycles/${cycle.id}/pay`,{operationId:payId,paymentNumber:'PAY-CHANGED'})).status,409);
    await create(`/api/v1/hr/payroll/cycles/${cycle.id}/adjustments`,{operationId:crypto.randomUUID(),employeeId:employee.id,adjustmentNumber:'ADJ-1',adjustmentType:'recovery',amount:'25000',currency:'IQD',reason:'تسوية اختبار'});

    const box=(await create('/api/v1/treasury/cashboxes',{code:'MAIN-IQD',name:'الصندوق الرئيسي',currency:'IQD'})).cashbox;
    const opened=(await create(`/api/v1/treasury/cashboxes/${box.id}/open`,{operationId:crypto.randomUUID(),sessionNumber:'SHIFT-1',openingBalance:'100'})).session;
    const priorMovement=await request(`/api/v1/treasury/cashboxes/${box.id}/movements`,{operationId:crypto.randomUUID(),movementNumber:'CASH-PRIOR',direction:'in',amount:'1',counterAccountCode:'3000-EQUITY',occurredAt:new Date(Date.parse(opened.openedAt)-1000).toISOString()});
    assert.equal(priorMovement.status,400,'cashbox movements cannot predate the session');
    const movementInput={operationId:crypto.randomUUID(),movementNumber:'CASH-1',direction:'out',amount:'25',counterAccountCode:'5100-COGS',reference:'مصروف تجريبي'};
    const movement=(await create(`/api/v1/treasury/cashboxes/${box.id}/movements`,movementInput)).movement;
    const cashJournalCount=runtime.store.journalEntries.size;
    await create(`/api/v1/treasury/cashboxes/${box.id}/movements`,movementInput);
    assert.equal(runtime.store.journalEntries.size,cashJournalCount,'cash movement retry is idempotent');
    assert.equal((await request(`/api/v1/treasury/cashboxes/${box.id}/movements`,{...movementInput,amount:'26'})).status,409);
    const insufficient=await request(`/api/v1/treasury/cashboxes/${box.id}/movements`,{...movementInput,operationId:crypto.randomUUID(),movementNumber:'CASH-TOO-MUCH',amount:'100'});
    assert.equal(insufficient.status,409);assert.equal(insufficient.data.error.code,'INSUFFICIENT_CASH');
    const closeInput={operationId:crypto.randomUUID(),countedBalance:'70'};
    const closed=(await request(`/api/v1/treasury/cashboxes/${box.id}/sessions/${opened.id}/close`,closeInput));
    assert.equal(closed.status,200,JSON.stringify(closed.data));
    assert.equal(closed.data.session.expectedBalance,'75.000000');
    assert.equal(closed.data.session.variance,'-5.000000');
    assert.equal((await request(`/api/v1/treasury/cashboxes/${box.id}/sessions/${opened.id}/close`,closeInput)).data.session.id,opened.id);
    assert.equal((await request(`/api/v1/treasury/cashboxes/${box.id}/movements`,null)).data.movements.length,1);

    const unit=(await create('/api/v1/catalog/units',{code:'PC',name:'قطعة'})).unit;
    const warehouse=(await create('/api/v1/warehouses',{code:'IMPORT',name:'مخزن الاستيراد'})).warehouse;
    const item=(await create('/api/v1/catalog/items',{sku:'IMP-1',name:'مادة مستوردة',baseUnitId:unit.id})).item;
    const supplier=(await create('/api/v1/suppliers',{code:'SUP-1',name:'مورد الاستيراد'})).supplier;
    const purchase=(await create('/api/v1/commerce/commit',{operationId:crypto.randomUUID(),deviceId:'test',clientSequence:1,occurredAt:new Date().toISOString(),document:{documentType:'purchase',documentNumber:'IMP-PUR-1',warehouseId:warehouse.id,partyId:supplier.id,currency:'IQD',lines:[{itemId:item.id,unitId:unit.id,quantity:'10',unitPrice:'100'}],payments:[]}})).result.document;
    const shipment=(await create('/api/v1/import/shipments',{operationId:crypto.randomUUID(),shipmentNumber:'SHIP-1',containerNumber:'CONT-1',supplierId:supplier.id,currency:'USD',origin:'البصرة',billOfLading:'BL-1'})).shipment;
    const arrived=await request(`/api/v1/import/shipments/${shipment.id}/arrival`,{operationId:crypto.randomUUID(),arrivedAt:new Date().toISOString()});
    assert.equal(arrived.status,200,JSON.stringify(arrived.data));
    await request(`/api/v1/import/shipments/${shipment.id}/purchase-document`,{operationId:crypto.randomUUID(),purchaseDocumentId:purchase.id});
    const costInput={operationId:crypto.randomUUID(),currency:'IQD',charges:[{code:'freight',description:'أجور الشحن',amount:'20'}],allocations:[{itemId:item.id,amount:'20'}]};
    const landed=(await create(`/api/v1/import/shipments/${shipment.id}/costs`,costInput)).cost;
    assert.equal(landed.capitalizedAmount,'20.000000');
    const companyId=[...runtime.store.companies.values()][0].id;
    assert.equal(runtime.store.stockBalances.get(`${companyId}:${warehouse.id}:${item.id}`).averageCost,'102.000000');
    const importsJournalCount=runtime.store.journalEntries.size;
    await create(`/api/v1/import/shipments/${shipment.id}/costs`,costInput);
    assert.equal(runtime.store.journalEntries.size,importsJournalCount,'landed-cost retry does not post a second journal');
    assert.equal((await request(`/api/v1/import/shipments/${shipment.id}/costs`,{...costInput,allocations:[{itemId:item.id,amount:'21'}],charges:[{code:'freight',description:'أجور الشحن',amount:'21'}]})).status,409);
    await request('/api/v1/auth/login',{companyCode:'local',username:'branch_keeper',password:'Strong-Branch-123'});
    assert.equal((await request('/api/v1/import/shipments',null,'GET')).data.shipments.some(row=>row.id===shipment.id),false,'branch users cannot view another branch shipment');
    const branchShipment=(await create('/api/v1/import/shipments',{operationId:crypto.randomUUID(),shipmentNumber:'BR-SHIP',containerNumber:'BR-CONT',supplierId:supplier.id,currency:'IQD'})).shipment;
    assert.equal((await request(`/api/v1/import/shipments/${branchShipment.id}/arrival`,{operationId:crypto.randomUUID(),arrivedAt:new Date().toISOString()})).status,200);
    assert.equal((await request(`/api/v1/import/shipments/${branchShipment.id}/purchase-document`,{operationId:crypto.randomUUID(),purchaseDocumentId:purchase.id})).status,403,'branch shipment cannot link a purchase from outside its branch');
    cookie=ownerCookie;

    for(const journal of runtime.store.journalEntries.values()) {
      const total=journal.lines.reduce((sum,line)=>sum+BigInt(line.debit.replace('.',''))-BigInt(line.credit.replace('.','')),0n);
      assert.equal(total,0n,`journal ${journal.entryNumber} is balanced`);
    }
    await runtime.close();runtime=null;
    runtime=await startEnterpriseLocal({dataDirectory:directory,port:33220});
    assert.equal(runtime.store.payrollCycles.size,1);
    assert.equal(runtime.store.payrollCycles.get(cycle.id).status,'paid');
    assert.equal(runtime.store.cashboxMovements.size,1);
    assert.equal(runtime.store.importCostPostings.size,1);
    assert.equal(runtime.store.leaveRequests.get(leave.id).status,'approved');
    assert.equal(runtime.store.overtimeRequests.get(overtime.id).status,'approved');
    assert.equal(runtime.store.attendanceEvents.size,2);
  } finally { if(runtime) await runtime.close(); await rm(directory,{recursive:true,force:true}); }
});
