import assert from 'node:assert/strict';
import { after, before, test } from 'node:test';
import { createApp } from '../../apps/api/src/app.js';
import { hashPassword } from '../../apps/api/src/lib/security.js';
import { decimal } from '../../apps/api/src/lib/decimal.js';
import { MemoryStore } from '../../apps/api/src/store/memory-store.js';

let server,baseUrl,store,admin,repToken,supervisor,otherAdmin;const id={};let sequence=1;
before(async()=>{store=new MemoryStore();const platform=await store.seedPlatformAdmin({username:'platform_rep',passwordHash:await hashPassword('Platform-Rep-123')});for(const code of ['rep_a','rep_b']){const c=await store.registerCompany({code,legalName:code,timezone:'Asia/Baghdad',currency:'IQD',owner:{username:'admin',displayName:'Admin',passwordHash:await hashPassword('Company-Rep-123')}});await store.approveCompany(c.id,platform.id)}const app=createApp({store});await new Promise(r=>{server=app.listen(0,'127.0.0.1',r)});baseUrl=`http://127.0.0.1:${server.address().port}`;admin=(await request('/api/v1/auth/login',{method:'POST',body:{companyCode:'rep_a',username:'admin',password:'Company-Rep-123'}})).data.token;otherAdmin=(await request('/api/v1/auth/login',{method:'POST',body:{companyCode:'rep_b',username:'admin',password:'Company-Rep-123'}})).data.token;await setup()});
after(async()=>new Promise(r=>server.close(r)));
async function request(path,{token,body,...options}={}){const response=await fetch(`${baseUrl}${path}`,{...options,headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});return{status:response.status,data:response.status===204?null:await response.json()}}
async function create(path,body,token=admin){const r=await request(path,{method:'POST',token,body});assert.equal(r.status,201,JSON.stringify(r.data));return r.data}
async function setup(){id.unit=(await create('/api/v1/catalog/units',{code:'PC',name:'قطعة'})).unit;id.item=(await create('/api/v1/catalog/items',{sku:'REP-ITEM',name:'مادة سيارة',baseUnitId:id.unit.id})).item;await create('/api/v1/catalog/prices',{itemId:id.item.id,unitId:id.unit.id,priceType:'sale',currency:'IQD',amount:'10.000000'});await create('/api/v1/catalog/barcodes',{itemId:id.item.id,unitId:id.unit.id,barcode:'REP0001'});id.customer=(await create('/api/v1/customers',{code:'REP-CUST',name:'عميل المسار',creditLimit:'100.000000'})).customer;id.supplier=(await create('/api/v1/suppliers',{code:'REP-SUP',name:'مورد'})).supplier;id.main=(await create('/api/v1/warehouses',{code:'MAIN',name:'الرئيسي'})).warehouse;id.vehicle=(await create('/api/v1/warehouses',{code:'CAR-1',name:'سيارة 1',kind:'vehicle'})).warehouse;const user=(await create('/api/v1/users',{username:'rep',displayName:'مندوب',password:'Representative-123',roleCode:'representative'})).user;const sup=(await create('/api/v1/users',{username:'supervisor',displayName:'مشرف',password:'Supervisor-123',roleCode:'representative_supervisor'})).user;id.rep=(await create('/api/v1/representatives',{userId:user.id,vehicleWarehouseId:id.vehicle.id,code:'R-1',name:'مندوب 1',deviceId:'rep-phone'})).representative;await request(`/api/v1/representatives/${id.rep.id}/customers/${id.customer.id}`,{method:'PUT',token:admin,body:{visitOrder:1,creditLimit:'100.000000'}});await create(`/api/v1/representatives/${id.rep.id}/routes`,{code:'ROUTE-1',name:'المسار الصباحي',stops:[{customerId:id.customer.id,stopOrder:1}]});repToken=(await request('/api/v1/auth/login',{method:'POST',body:{companyCode:'rep_a',username:'rep',password:'Representative-123',deviceId:'rep-phone'}})).data.token;supervisor=(await request('/api/v1/auth/login',{method:'POST',body:{companyCode:'rep_a',username:'supervisor',password:'Supervisor-123'}})).data.token;await request('/api/v1/commerce/commit',{method:'POST',token:admin,body:{operationId:crypto.randomUUID(),deviceId:'setup',clientSequence:1,occurredAt:new Date().toISOString(),document:{documentType:'purchase',documentNumber:'REP-STOCK',warehouseId:id.main.id,partyId:id.supplier.id,currency:'IQD',lines:[{itemId:id.item.id,unitId:id.unit.id,quantity:'20.000000',unitPrice:'5.000000'}],payments:[]}}});}
function op(type,payload,deviceId='rep-phone'){return{operationId:crypto.randomUUID(),deviceId,clientSequence:sequence++,occurredAt:new Date().toISOString(),type,payload:{representativeId:id.rep.id,...payload}}}
async function send(token,type,payload,existing){const body=existing||op(type,payload);return{body,response:await request('/api/v1/representatives/operations',{method:'POST',token,body})}}

test('representative setup, route, vehicle stock transfer and tenant boundaries',async()=>{const forbidden=await request(`/api/v1/representatives/${id.rep.id}/routes`,{method:'POST',token:repToken,body:{code:'NO',name:'No',stops:[{customerId:id.customer.id}]}});assert.equal(forbidden.status,403);const cross=await request(`/api/v1/representatives/bootstrap?representativeId=${id.rep.id}`,{token:otherAdmin});assert.equal(cross.status,404);const loaded=await send(admin,'representative.load',{sourceWarehouseId:id.main.id,transferNumber:'LOAD-1',lines:[{itemId:id.item.id,quantity:'10.000000'}]});assert.equal(loaded.response.status,201,JSON.stringify(loaded.response.data));const boot=await request('/api/v1/representatives/bootstrap',{token:repToken});assert.equal(boot.status,200);assert.equal(boot.data.stock[0].quantity,'10.000000');assert.equal(boot.data.customers[0].id,id.customer.id);assert.equal(boot.data.routes[0].stops[0].customerId,id.customer.id);assert.equal(boot.data.catalog[0].barcode,'REP0001')});

test('offline-style replay is idempotent and sale posts stock, debt, custody and revenue once',async()=>{const sold=await send(repToken,'representative.sale',{partyId:id.customer.id,documentNumber:'REP-SALE-1',currency:'IQD',originalDocumentId:null,lines:[{itemId:id.item.id,unitId:id.unit.id,originalLineId:null,quantity:'5.000000',unitPrice:'10.000000'}],payments:[{method:'cash',amount:'20.000000',reference:null}],discountAmount:'0.000000'});assert.equal(sold.response.status,201,JSON.stringify(sold.response.data));id.sale=sold.response.data.result.document;const replay=await request('/api/v1/representatives/operations',{method:'POST',token:repToken,body:sold.body});assert.equal(replay.status,201);assert.equal(replay.data.result.entityId,id.sale.id);assert.equal([...store.commerceDocuments.values()].filter(x=>x.documentNumber==='REP-SALE-1').length,1);assert.equal([...store.debtMovements.values()].reduce((s,x)=>s+decimal(x.amount),0n),decimal('30.000000'));assert.equal([...store.custodyMovements.values()].reduce((s,x)=>s+decimal(x.amount),0n),decimal('20.000000'));const journal=[...store.journalEntries.values()].find(x=>x.documentId===id.sale.id);assert.equal(journal.lines.filter(x=>x.account==='4100-SALES').length,1);assert.ok(journal.lines.some(x=>x.account==='1150-REP-CASH-CUSTODY'));assert.equal([...store.stockBalances.values()].find(x=>x.warehouseId===id.vehicle.id).quantity,'5.000000')});

test('representative return reverses the proportional debt, custody and vehicle stock',async()=>{const returned=await send(repToken,'representative.return',{partyId:id.customer.id,documentNumber:'REP-RETURN-1',currency:'IQD',originalDocumentId:id.sale.id,lines:[{itemId:id.item.id,unitId:id.unit.id,originalLineId:id.sale.lines[0].id,quantity:'1.000000'}],payments:[{method:'cash',amount:'4.000000',reference:'REP-SALE-1'}],discountAmount:'0.000000'});assert.equal(returned.response.status,201,JSON.stringify(returned.response.data));assert.equal(returned.response.data.result.document.dueAmount,'6.000000');assert.equal([...store.debtMovements.values()].reduce((s,x)=>s+decimal(x.amount),0n),decimal('24.000000'));assert.equal([...store.custodyMovements.values()].reduce((s,x)=>s+decimal(x.amount),0n),decimal('16.000000'));assert.equal([...store.stockBalances.values()].find(x=>x.warehouseId===id.vehicle.id).quantity,'6.000000')});

test('credit and stock failures are atomic, retained as conflicts and retry safely',async()=>{const before={docs:store.commerceDocuments.size,stock:[...store.stockBalances.values()].find(x=>x.warehouseId===id.vehicle.id).quantity};const failed=await send(repToken,'representative.sale',{partyId:id.customer.id,documentNumber:'REP-CREDIT-FAIL',currency:'IQD',originalDocumentId:null,lines:[{itemId:id.item.id,unitId:id.unit.id,originalLineId:null,quantity:'5.000000',unitPrice:'20.000000'}],payments:[],discountAmount:'0.000000'});assert.equal(failed.response.status,409);assert.equal(failed.response.data.result.code,'CREDIT_LIMIT_EXCEEDED');assert.equal(store.commerceDocuments.size,before.docs);assert.equal([...store.stockBalances.values()].find(x=>x.warehouseId===id.vehicle.id).quantity,before.stock);const retry=await request('/api/v1/representatives/operations',{method:'POST',token:repToken,body:failed.body});assert.equal(retry.data.result.code,'CREDIT_LIMIT_EXCEEDED');const status=await request('/api/v1/sync/status',{token:repToken});assert.ok(status.data.conflicts>=1)});

test('collection reduces debt, increases custody without duplicate revenue, then supervisor settles cash and goods',async()=>{const salesBefore=[...store.journalEntries.values()].flatMap(x=>x.lines).filter(x=>(x.accountCode||x.account)==='4100-SALES').length;const collected=await send(repToken,'representative.collection',{customerId:id.customer.id,receiptNumber:'COL-1',amount:'10.000000',currency:'IQD'});assert.equal(collected.response.status,201,JSON.stringify(collected.response.data));assert.equal([...store.debtMovements.values()].reduce((s,x)=>s+decimal(x.amount),0n),decimal('14.000000'));assert.equal([...store.custodyMovements.values()].reduce((s,x)=>s+decimal(x.amount),0n),decimal('26.000000'));assert.equal([...store.journalEntries.values()].flatMap(x=>x.lines).filter(x=>(x.accountCode||x.account)==='4100-SALES').length,salesBefore);id.handover=crypto.randomUUID();const submitted=await send(repToken,'representative.handover.submit',{handoverId:id.handover,destinationWarehouseId:id.main.id,handoverNumber:'HND-1',submittedCash:'26.000000',currency:'IQD',lines:[{itemId:id.item.id,quantity:'1.000000'}]});assert.equal(submitted.response.status,201);assert.equal(submitted.response.data.result.handover.status,'submitted');const reviewed=await send(supervisor,'representative.handover.review',{handoverId:id.handover,reviewedCash:'26.000000'},op('representative.handover.review',{handoverId:id.handover,reviewedCash:'26.000000'},'supervisor'));assert.equal(reviewed.response.status,201,JSON.stringify(reviewed.response.data));assert.equal(reviewed.response.data.result.handover.status,'reviewed');assert.equal([...store.custodyMovements.values()].reduce((s,x)=>s+decimal(x.amount),0n),0n);assert.equal([...store.stockBalances.values()].find(x=>x.warehouseId===id.vehicle.id).quantity,'5.000000');assert.equal([...store.stockBalances.values()].find(x=>x.warehouseId===id.main.id).quantity,'11.000000')});
