import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { startEnterpriseCloud } from '../../apps/api/src/cloud-server.js';

test('sales workspace isolates channels, enforces exact approvals, reservations, prices and persists customer/service data',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'sales-workspace-'));let rt;
 try{
  rt=await startEnterpriseCloud({dataDirectory:dir,setupToken:'sales-test-key-123456789012345678',origin:'https://example.test',port:0});
  const request=async(path,body,cookie='',method='POST')=>{const r=await fetch(rt.url+path,{headers:{Cookie:cookie,'Content-Type':'application/json'},...(body?{method,body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
  await request('/api/local/setup',{setupToken:'sales-test-key-123456789012345678',legalName:'اختبار',ownerName:'مدير',username:'admin',password:'Strong-Password-123'});
  const manager=(await request('/api/v1/auth/login',{companyCode:'company',username:'admin',password:'Strong-Password-123'})).cookie;
  const create=async(path,body)=>{const r=await request(path,body,manager);assert.equal(r.status,201,JSON.stringify(r.data));return r.data;};
  const unit=(await create('/api/v1/catalog/units',{code:'PC',name:'قطعة'})).unit;
  const item=(await create('/api/v1/catalog/items',{sku:'A',name:'صنف',baseUnitId:unit.id})).item;
  const warehouse=(await create('/api/v1/warehouses',{code:'WH',name:'مخزن'})).warehouse;
  const customer=(await create('/api/v1/customers',{code:'C',name:'زبون مفرد',phone:'07700000000',creditLimit:'1000'})).customer;
  const wholesale=(await create('/api/v1/customers',{code:'CW',name:'زبون جملة',creditLimit:'1000'})).customer;
  const rep=(await create('/api/v1/users',{username:'seller',displayName:'حسن كاظم',roleCode:'representative',password:'Strong-Seller-123'})).user;
  const other=(await create('/api/v1/users',{username:'wholesale',displayName:'مندوب جملة',roleCode:'representative',password:'Strong-Seller-123'})).user;
  const setting=async(type,id,body)=>{const r=await request('/api/v1/sales/settings/'+type+'/'+id,body,manager,'PUT');assert.equal(r.status,200,JSON.stringify(r.data));};
  await setting('user',rep.id,{channel:'retail',phone:'0771',location:'بغداد',maxDiscountPercent:'5'});
  await setting('user',other.id,{channel:'wholesale',maxDiscountPercent:'5'});
  await setting('customer',customer.id,{channel:'retail',risk:'yellow',governorate:'بغداد',district:'الكرخ',neighborhood:'المنصور'});
  await setting('customer',wholesale.id,{channel:'wholesale',risk:'green'});
  await setting('item',item.id,{channel:'wholesale',movement:'strong',maxDiscountPercent:'3',warehouseId:warehouse.id,reservedQuantity:'8'});
  await create('/api/v1/catalog/prices',{itemId:item.id,unitId:unit.id,priceType:'sale_retail',currency:'IQD',amount:'10'});
  await create('/api/v1/catalog/prices',{itemId:item.id,unitId:unit.id,priceType:'sale_wholesale',currency:'IQD',amount:'8'});
  const seller=(await request('/api/v1/auth/login',{companyCode:'company',username:'seller',password:'Strong-Seller-123'})).cookie;
  const wholeCookie=(await request('/api/v1/auth/login',{companyCode:'company',username:'wholesale',password:'Strong-Seller-123'})).cookie;
  const retailManager=(await create('/api/v1/users',{username:'retail-manager',displayName:'مدير المفرد',roleCode:'cashier',password:'Strong-Manager-123'})).user;
  const wholeManager=(await create('/api/v1/users',{username:'whole-manager',displayName:'مدير الجملة',roleCode:'cashier',password:'Strong-Manager-123'})).user;
  await setting('user',retailManager.id,{channel:'retail',salesManager:true});await setting('user',wholeManager.id,{channel:'wholesale',salesManager:true});
  const retailManagerCookie=(await request('/api/v1/auth/login',{companyCode:'company',username:'retail-manager',password:'Strong-Manager-123'})).cookie;
  const wholeManagerCookie=(await request('/api/v1/auth/login',{companyCode:'company',username:'whole-manager',password:'Strong-Manager-123'})).cookie;
  const personal=[{id:'note-1',kind:'note',text:'ملاحظتي الخاصة',done:false},{id:'reminder-1',kind:'reminder',text:'اتصال بالزبون',dueAt:'2026-10-08T10:00:00Z',done:false}];
  assert.equal((await request('/api/v1/sales/personal-board',{cards:personal,userId:other.id},seller,'PUT')).status,200);
  assert.equal((await request('/api/v1/sales/bootstrap',null,wholeCookie)).data.personalCards.length,0);
  assert.equal((await request('/api/v1/sales/bootstrap',null,manager)).data.personalCards.length,0);
  assert.equal((await request('/api/v1/sales/personal-board',{cards:[{id:'bad',kind:'reminder',text:'bad',dueAt:'invalid'}]},seller,'PUT')).status,400);
  const commit=async(document,cookie=manager,id=crypto.randomUUID())=>request('/api/v1/commerce/commit',{operationId:id,deviceId:'test',clientSequence:Date.now(),occurredAt:new Date().toISOString(),document},cookie);
  const purchase={documentType:'purchase',documentNumber:'P1',warehouseId:warehouse.id,currency:'IQD',lines:[{itemId:item.id,unitId:unit.id,quantity:'10',unitPrice:'4'}],payments:[]};
  assert.equal((await commit(purchase)).status,201);
  const boot=(await request('/api/v1/sales/bootstrap',null,seller)).data;assert.deepEqual(boot.customers.map(x=>x.id),[customer.id]);assert.deepEqual(boot.prices.map(x=>x.priceType),['sale_retail']);assert.equal(boot.profile.phone,'0771');assert.equal(boot.stock[0].averageCost,undefined);
  const master=(await request('/api/v1/master-data',null,seller)).data;assert.deepEqual(master.customers.map(x=>x.id),[customer.id]);assert.deepEqual(master.prices.map(x=>x.priceType),['sale_retail']);
  const sale={documentType:'sale',documentNumber:'S1',warehouseId:warehouse.id,partyId:customer.id,currency:'IQD',lines:[{itemId:item.id,unitId:unit.id,quantity:'4',unitPrice:'10'}],discountAmount:'4',delivery:{mode:'both',deliveryAt:'2026-10-08T12:00:00Z',serviceAt:'2026-10-08T14:00:00Z'},payments:[{method:'cash',amount:'10'}]};
  assert.equal((await commit(sale,seller)).data.result.code,'MANAGER_APPROVAL_REQUIRED');
  assert.equal((await commit({...sale,partyId:wholesale.id},seller)).data.result.code,'CUSTOMER_SCOPE');
  assert.equal((await commit({...sale,lines:[{...sale.lines[0],unitPrice:'8'}]},seller)).data.result.code,'PRICE_CHANGED');
  const asked=await request('/api/v1/sales/approvals',{document:sale},seller);assert.equal(asked.status,201,JSON.stringify(asked.data));const id=asked.data.approval.id;
  assert.equal((await request('/api/v1/sales/approvals/'+id+'/decision',{status:'approved'},seller)).status,403);
  assert.equal(asked.data.approval.managerUserId,retailManager.id);assert.equal((await request('/api/v1/sales/bootstrap',null,wholeManagerCookie)).data.approvals.length,0);assert.equal((await request('/api/v1/sales/approvals/'+id+'/decision',{status:'approved'},wholeManagerCookie)).status,403);assert.equal((await request('/api/v1/sales/approvals/'+id+'/decision',{status:'approved'},retailManagerCookie)).status,200);
  assert.equal((await commit({...sale,approvalId:id,lines:[{...sale.lines[0],quantity:'5'}]},seller)).data.result.code,'MANAGER_APPROVAL_REQUIRED');
  assert.equal((await commit({...sale,approvalId:id,partyId:wholesale.id},wholeCookie)).data.result.code,'PRICE_CHANGED');
  const op=crypto.randomUUID(),posted=await commit({...sale,approvalId:id},seller,op);assert.equal(posted.status,201,JSON.stringify(posted.data));assert.equal(posted.data.result.document.assignedSalesManagerId,retailManager.id);assert.equal(posted.data.result.document.subtotal,'36.000000');assert.equal(posted.data.result.document.dueAmount,'26.000000');assert.equal(posted.data.result.document.delivery.mode,'both');
  assert.equal((await commit({...sale,approvalId:id},seller,op)).data.result.entityId,posted.data.result.entityId);
  assert.equal((await commit({...sale,approvalId:id,documentNumber:'REUSE'},seller)).data.result.code,'MANAGER_APPROVAL_REQUIRED');
  assert.equal((await request('/api/v1/sales/customer-review',{customerId:wholesale.id},seller)).status,403);
  assert.equal((await request('/api/v1/sales/customer-review',{customerId:customer.id},seller)).status,201);
  const walk=await request('/api/v1/sales/walk-in',{name:'زبون مرة واحدة',address:'بغداد',phone:'0772',channel:'wholesale'},seller);assert.equal(walk.status,201);assert.equal(walk.data.customer.channel,'retail');assert.equal(walk.data.customer.neighborhood,'بغداد');
  assert.equal((await request('/api/v1/sales/bootstrap',null,wholeCookie)).data.documents.length,0);
  const sync=(await request('/api/v1/sync/pull?cursor=0',null,seller)).data;assert.ok(!sync.changes.some(x=>x.entityType==='price'&&x.payload.priceType==='sale_wholesale'));
  await rt.close();rt=await startEnterpriseCloud({dataDirectory:dir,setupToken:'sales-test-key-123456789012345678',origin:'https://example.test',port:0});
  const persisted=(await request('/api/v1/sales/bootstrap',null,seller)).data;assert.equal(persisted.personalCards.length,2);assert.equal(persisted.personalCards[1].dueAt,'2026-10-08T10:00:00.000Z');assert.equal(persisted.profile.location,'بغداد');assert.equal(persisted.approvals[0].status,'used');assert.equal(persisted.items[0].reserved[warehouse.id],'6.000000');assert.equal(persisted.customers.find(x=>x.id===customer.id).risk,'yellow');assert.equal(persisted.reviews.length,1);assert.equal(persisted.documents[0].delivery.serviceAt,'2026-10-08T14:00:00.000Z');
  await setting('warehouse',warehouse.id,{damaged:true});assert.equal((await commit({...sale,documentNumber:'DAMAGE'},seller)).data.result.code,'DAMAGED_WAREHOUSE');
 }finally{if(rt)await rt.close();await rm(dir,{recursive:true,force:true});}
});
