import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {startEnterpriseCloud} from '../../apps/api/src/cloud-server.js';
test('user editor saves sales type, manager assignment and extra permissions atomically, routes invoices and persists',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'user-sales-profile-')),options={dataDirectory:dir,setupToken:'users-profile-key-123456789012345',origin:'https://example.test',port:0};let rt;
 try{rt=await startEnterpriseCloud(options);
 const request=async(path,body,cookie='',method=body?'POST':'GET')=>{const r=await fetch(rt.url+path,{method,headers:{Cookie:cookie,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return{status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
 await request('/api/local/setup',{setupToken:options.setupToken,legalName:'شركة اختبار',ownerName:'مدير',username:'admin',password:'Strong-Password-123'});
 const login=async username=>(await request('/api/v1/auth/login',{companyCode:'company',username,password:'Strong-Password-123'})).cookie,owner=await login('admin');
 const create=async(path,body)=>{const r=await request(path,body,owner);assert.equal(r.status,201,JSON.stringify(r.data));return r.data;};
 const wm=(await create('/api/v1/users',{username:'whole-manager',displayName:'مدير الجملة',password:'Strong-Password-123',roleCode:'representative_supervisor',salesProfile:{kind:'manager',channel:'wholesale'}})).user;
 const rm=(await create('/api/v1/users',{username:'retail-manager',displayName:'مدير المفرد',password:'Strong-Password-123',roleCode:'representative_supervisor',salesProfile:{kind:'manager',channel:'retail'}})).user;
 const managerCookie=await login('whole-manager'),retailManagerCookie=await login('retail-manager');assert.equal((await request('/api/v1/bootstrap',null,managerCookie)).data.salesProfile.salesManager,true);assert((await request('/api/v1/bootstrap',null,managerCookie)).data.permissions.includes('sales.approve'));
 const perms=['catalog.read','catalog.manage','customers.read','inventory.read','sales.read','sales.create','sales.return','sync.use'];
 const rep=(await create('/api/v1/users',{username:'seller',displayName:'مندوب الجملة',password:'Strong-Password-123',roleCode:'representative',permissions:perms,salesProfile:{kind:'representative',channel:'wholesale',managerUserId:wm.id,phone:'هاتف تجريبي',location:'بغداد',maxDiscountPercent:'0'}})).user,seller=await login('seller');
 const boot=(await request('/api/v1/sales/bootstrap',null,seller)).data;assert.equal(boot.profile.channel,'wholesale');assert.equal(boot.profile.managerUserId,wm.id);assert.equal(boot.profile.location,'بغداد');assert.equal((await request('/api/v1/catalog/units',{code:'EXTRA',name:'صلاحية إضافية'},seller)).status,201);
 const count=(await request('/api/v1/users',null,owner)).data.users.length;
 const invalid={username:'invalid',displayName:'غير صالح',password:'Strong-Password-123',roleCode:'representative',salesProfile:{kind:'representative',channel:'wholesale',managerUserId:rm.id}};assert.equal((await request('/api/v1/users',invalid,owner)).status,400);assert.equal((await request('/api/v1/users',{...invalid,salesProfile:{kind:'none'}},owner)).status,400);assert.equal((await request('/api/v1/users',null,owner)).data.users.length,count);
 const unit=(await create('/api/v1/catalog/units',{code:'PC',name:'قطعة'})).unit,item=(await create('/api/v1/catalog/items',{sku:'A',name:'مادة',baseUnitId:unit.id})).item,wh=(await create('/api/v1/warehouses',{code:'WH',name:'مخزن'})).warehouse;
 await create('/api/v1/catalog/prices',{itemId:item.id,unitId:unit.id,priceType:'sale_wholesale',amount:'10',currency:'IQD'});await create('/api/v1/catalog/prices',{itemId:item.id,unitId:unit.id,priceType:'sale_retail',amount:'20',currency:'IQD'});
 const commit=(document,cookie)=>request('/api/v1/commerce/commit',{operationId:crypto.randomUUID(),deviceId:'test',clientSequence:Date.now(),occurredAt:new Date().toISOString(),document},cookie);
 assert.equal((await commit({documentType:'purchase',documentNumber:'P1',warehouseId:wh.id,currency:'IQD',lines:[{itemId:item.id,unitId:unit.id,quantity:'10',unitPrice:'4'}],payments:[]},owner)).status,201);
 const customer=(await create('/api/v1/customers',{code:'C',name:'زبون جملة',creditLimit:'1000'})).customer;assert.equal((await request('/api/v1/sales/settings/customer/'+customer.id,{channel:'wholesale',risk:'green'},owner,'PUT')).status,200);
 const sale={partyId:customer.id,documentType:'sale',documentNumber:'S1',warehouseId:wh.id,currency:'IQD',lines:[{itemId:item.id,unitId:unit.id,quantity:'4',unitPrice:'10'}],discountAmount:'4',payments:[{method:'cash',amount:'36'}],delivery:{mode:'immediate'}};
 const approval=await request('/api/v1/sales/approvals',{document:sale},seller);assert.equal(approval.status,201,JSON.stringify(approval.data));assert.equal(approval.data.approval.managerUserId,wm.id);assert.equal((await request('/api/v1/sales/approvals/'+approval.data.approval.id+'/decision',{status:'approved'},retailManagerCookie)).status,403);assert.equal((await request('/api/v1/sales/approvals/'+approval.data.approval.id+'/decision',{status:'approved'},managerCookie)).status,200);
 const sold=await commit({...sale,approvalId:approval.data.approval.id},seller);assert.equal(sold.status,201,JSON.stringify(sold.data));assert.equal([...rt.store.commerceDocuments.values()].find(x=>x.documentNumber==='S1').assignedSalesManagerId,wm.id);
 const updated=await request('/api/v1/users/'+rep.id,{username:'seller',displayName:'مندوب مفرد',roleCode:'representative',status:'active',permissions:perms,salesProfile:{kind:'representative',channel:'retail',managerUserId:rm.id,maxDiscountPercent:'5',location:'المنصور'}},owner,'PUT');assert.equal(updated.status,200);assert.equal(updated.data.user.salesProfile.channel,'retail');assert.equal((await request('/api/v1/sales/bootstrap',null,seller)).data.prices[0].priceType,'sale_retail');
 await rt.close();rt=await startEnterpriseCloud(options);const persisted=(await request('/api/v1/users',null,owner)).data.users.find(x=>x.id===rep.id);assert.equal(persisted.salesProfile.managerUserId,rm.id);assert.equal(persisted.salesProfile.maxDiscountPercent,'5.000000');assert(persisted.permissions.includes('catalog.manage'));
 }finally{await rt?.close();await rm(dir,{recursive:true,force:true});}
});
