// Proposed opening catalogue. Prices are editable starting values, not supplier quotes.
export function furnitureCatalog(){
 const warehouses=[{code:'FUR-ROOMS',name:'مخزن غرف النوم والغرف الشبابية'},{code:'FUR-SOFAS',name:'مخزن التخم والكنبات'},{code:'FUR-HOME',name:'مخزن المنزلي والكنتورات والمكتبات'},{code:'FUR-DINING',name:'مخزن الطبلات وميز الطعام'},{code:'FUR-OFFICE',name:'مخزن الأثاث المكتبي والكراسي'}];
 const items=[],origins=[['صيني',1,['روبي','لورا'],'لين'],['تركي',1.35,['ميلانو','لاله'],'آسيا'],['ماليزي',1.18,['سيرينا','كوالا'],'نوفا'],['أوروبي',1.85,['فيرونا','فلورنس'],'إيلا'],['إيراني',1.1,['شيراز','ياسمين'],'باران']];let room=34,serial=1;
 function add({code,name,warehouse,origin='صيني',dimensions,colors=['أبيض','جوزي','رمادي'],retail,pieces=null,components=[],category,material='خشب صناعي MDF',size}){colors.forEach((color,index)=>items.push({sku:code+'-CLR'+(index+1),name:name+' — '+color,warehouseCode:warehouse,retail:Math.round(retail/1000)*1000,wholesale:Math.round(retail*.9/1000)*1000,metadata:{group:warehouse==='FUR-ROOMS'?'غرف نوم':warehouse==='FUR-SOFAS'?'تخم':warehouse==='FUR-OFFICE'?'مكتبي':'منزلي',catalog:'furniture-v1',demo:true,description:'مادة تجريبية قابلة للتعديل والحذف. '+name+'؛ صناعة '+origin+'؛ '+dimensions,pricesProvisional:true,modelCode:code,modelName:name,category,origin,color,colors,dimensions,material,size:size||dimensions,pieces,components}}));}
 const roomParts=(code,pieces,youth=false)=>{const parts=[['كنتور ملابس',1],['ميز تواليت مع مرآة',1],['سرير',1],['زاوية غرفة',1],[youth?'ميز دراسة':'كومود جانبي',1]];if(pieces>=7)parts.push(['بوف تسريحة',1],['شيفونيرة',1]);if(pieces===11)parts.push(['وحدة رفوف',1],['كرسي غرفة',2],['ميز جانبي',1]);return parts.map(([name,quantity],i)=>({code:code+'-'+(i+1),name,quantity}));};
 for(const [origin,factor,names,youthName] of origins){for(const name of names)for(const pieces of [5,7,11]){const code='C-'+room++;add({code,name:'غرفة نوم '+name+' '+pieces+' قطع',warehouse:'FUR-ROOMS',origin,dimensions:pieces===5?'سرير 160×200؛ كنتور 180×60×220 سم':pieces===7?'سرير 180×200؛ كنتور 240×60×220 سم':'سرير 200×200؛ كنتور 300×65×230 سم',retail:(1200000+(pieces-5)*160000)*factor,pieces,components:roomParts(code,pieces),category:'غرف نوم',material:'MDF / قشرة خشب، حسب الموديل'});}for(const pieces of [5,7]){const code='C-'+room++;add({code,name:'غرفة شبابية '+youthName+' '+pieces+' قطع',warehouse:'FUR-ROOMS',origin,colors:['أبيض وبلوط','رمادي وأزرق','بيج ووردي'],dimensions:pieces===5?'سرير 100×200؛ كنتور 120×55×200 سم':'سرير 120×200؛ كنتور 180×55×210 سم',retail:(850000+(pieces-5)*130000)*factor,pieces,components:roomParts(code,pieces,true),category:'غرف شبابية'});}}
 for(const [name,origin,base] of [['سلطان','تركي',1450000],['أزمير','تركي',1650000],['روما','أوروبي',2200000],['لين','صيني',850000],['كوالا','ماليزي',1050000],['شيراز','إيراني',1150000]])for(const seats of [5,7])add({code:'S-'+serial++,name:'تخم '+name+' '+seats+' مقاعد',warehouse:'FUR-SOFAS',origin,colors:['بيج','رمادي','زيتي'],dimensions:seats===5?'كنبة 210×90؛ كرسيان 90×90 سم':'كنبة 240×95؛ كنبة 180×95؛ كرسيان 95×95 سم',retail:base+(seats-5)*150000,pieces:seats===5?3:4,category:'تخم جلوس',material:'هيكل خشب وقماش',size:seats+' مقاعد'});
 for(const [name,origin,base] of [['إزمير','تركي',750000],['ماربل','صيني',450000],['فيرونا','أوروبي',1250000]])for(const seats of [4,6])add({code:'D-'+serial++,name:'ميز طعام '+name+' '+seats+' كراسي',warehouse:'FUR-DINING',origin,dimensions:seats===4?'ميز 120×80×75 سم':'ميز 180×90×75 سم',retail:base+(seats-4)*110000,pieces:seats+1,category:'ميز طعام',material:'خشب وسطح MDF / رخام صناعي',size:seats+' كراسي'});
 for(const [name,base,material] of [['نست',180000,'خشب ومعدن'],['ماربل',240000,'رخام صناعي ومعدن'],['روبي',150000,'خشب MDF']])for(const size of ['صغيرة','كبيرة'])add({code:'T-'+serial++,name:'طبلة '+name+' '+size,warehouse:'FUR-DINING',dimensions:size==='صغيرة'?'80×50×45 سم':'120×60×45 سم',retail:base+(size==='كبيرة'?70000:0),category:'طبلات',material,size});
 for(const doors of [2,3])for(const height of [180,220])add({code:'H-'+serial++,name:'كنتور '+doors+' أبواب ارتفاع '+height,warehouse:'FUR-HOME',origin:'ماليزي',dimensions:(doors===2?'90':'135')+'×55×'+height+' سم',retail:260000+(doors-2)*120000+(height-180)*2500,category:'كنتورات',size:doors+' أبواب'});
 for(const [name,width,base] of [['مكتبة مفتوحة',80,180000],['مكتبة بأبواب',100,260000],['مكتبة زاوية',90,230000]])add({code:'B-'+serial++,name,warehouse:'FUR-HOME',dimensions:width+'×35×190 سم',retail:base,category:'مكتبات'});
 for(const [name,origin,base] of [['ميز مدير','تركي',650000],['ميز موظف','صيني',210000],['ميز حاسوب','ماليزي',260000]])for(const width of [120,160])add({code:'O-'+serial++,name:name+' '+width+' سم',warehouse:'FUR-OFFICE',origin,dimensions:width+'×70×75 سم',retail:base+(width-120)*3000,category:'ميوز مكتبي',colors:['بلوط فاتح','جوزي','رمادي']});
 for(const [name,origin,base] of [['كرسي مدير','تركي',230000],['كرسي موظف شبك','صيني',115000],['كرسي زائر','ماليزي',85000]])for(const size of ['قياسي','كبير'])add({code:'Q-'+serial++,name:name+' '+size,warehouse:'FUR-OFFICE',origin,dimensions:size==='قياسي'?'عرض المقعد 48؛ عمق 48 سم':'عرض المقعد 55؛ عمق 52 سم',retail:base+(size==='كبير'?35000:0),category:'كراسي مكتبي',material:'معدن / شبك / جلد صناعي',colors:['أسود','رمادي','بيج'],size});
 return {version:'furniture-v1',warehouses,items};
}
